name: sales_reporting
description: ''
version: '1.0'
author: maciej+webinar-2022@prophecy.io
language: python
buildSystem: wheel
pipelines:
  pipelines/monthly_reporting:
    name: monthly_reporting
    description: ''
    author: maciej+webinar-2022@prophecy.io
    mode: batch
    language: python
    createdAt: '2022-11-03 17:26:29'
    datasets:
      inputs:
      - datasets/customers_nations
      - datasets/nations
      - datasets/regions
      - datasets/silver_orders_sales_2
      - datasets/silver_sales_customers
      outputs:
      - datasets/final_gold_report
    dependencies: {}
  pipelines/mrr_reporting:
    name: mrr_reporting
    description: ''
    author: maciej+webinar-2022@prophecy.io
    mode: batch
    language: python
    createdAt: '2022-11-03 15:48:16'
    datasets:
      inputs:
      - datasets/customers_nations
      - datasets/nations
      - datasets/regions
      - datasets/silver_sales_customers
      - datasets/silver_sales_orders
      outputs:
      - datasets/final_report
    dependencies: {}
  pipelines/orders_cleanup:
    name: orders_cleanup
    description: ''
    author: maciej+webinar-2022@prophecy.io
    mode: batch
    language: python
    createdAt: '2022-11-03 15:42:03'
    datasets:
      inputs:
      - gitUri=http://gitserver:3000/pM1sUhx1_team_2518/pM1sUhx1_project_3890.git&subPath=&tag=saas_ingestion/1.0&projectSubscriptionProjectId=3890&path=datasets/bronze_orders
      outputs:
      - datasets/silver_sales_orders
    dependencies: {}
  pipelines/customers_cleanup:
    name: customers_cleanup
    description: ''
    author: maciej+webinar-2022@prophecy.io
    mode: batch
    language: python
    createdAt: '2022-11-03 15:38:31'
    datasets:
      inputs:
      - gitUri=http://gitserver:3000/pM1sUhx1_team_2518/pM1sUhx1_project_3890.git&subPath=&tag=saas_ingestion/1.0&projectSubscriptionProjectId=3890&path=datasets/bronze_customers
      outputs:
      - datasets/silver_sales_customers
    dependencies: {}
  pipelines/qwe:
    name: qwe
    description: null
    author: maciej+webinar-2022@prophecy.io
    mode: batch
    language: python
    createdAt: '2023-01-12 17:28:29'
    datasets:
      inputs: []
      outputs: []
    dependencies: {}
  pipelines/fedex_demo:
    name: fedex_demo
    description: null
    author: maciej+webinar-2022@prophecy.io
    mode: batch
    language: python
    createdAt: '2023-01-12 06:54:12'
    datasets:
      inputs: []
      outputs: []
    dependencies: {}
datasets:
  datasets/customers_nations:
    name: customers_nations
    description: ''
    author: maciej+webinar-2022@prophecy.io
    createdAt: '2022-11-03 15:52:55'
    mode: batch
    physicalDatasets:
      dev:
        fabricId: 1034
        datasetType: File
        description: ''
        author: maciej+webinar-2022@prophecy.io
        createdAt: '2022-11-03 15:52:55'
  datasets/regions:
    name: regions
    description: ''
    author: maciej+webinar-2022@prophecy.io
    createdAt: '2022-11-03 15:53:47'
    mode: batch
    physicalDatasets:
      dev:
        fabricId: 1034
        datasetType: File
        description: ''
        author: maciej+webinar-2022@prophecy.io
        createdAt: '2022-11-03 15:53:47'
  datasets/final_gold_report:
    name: final_gold_report
    description: ''
    author: maciej+webinar-2022@prophecy.io
    createdAt: '2022-11-03 17:33:25'
    mode: batch
    physicalDatasets:
      dev:
        fabricId: 1034
        datasetType: Database
        description: ''
        author: maciej+webinar-2022@prophecy.io
        createdAt: '2022-11-03 17:33:25'
  datasets/nations:
    name: nations
    description: ''
    author: maciej+webinar-2022@prophecy.io
    createdAt: '2022-11-03 15:53:21'
    mode: batch
    physicalDatasets:
      dev:
        fabricId: 1034
        datasetType: File
        description: ''
        author: maciej+webinar-2022@prophecy.io
        createdAt: '2022-11-03 15:53:21'
  datasets/silver_sales_customers:
    name: silver_sales_customers
    description: ''
    author: maciej+webinar-2022@prophecy.io
    createdAt: '2022-11-03 15:39:51'
    mode: batch
    physicalDatasets:
      dev:
        fabricId: 1034
        datasetType: Database
        description: ''
        author: maciej+webinar-2022@prophecy.io
        createdAt: '2022-11-03 15:39:51'
  datasets/silver_sales_orders:
    name: silver_sales_orders
    description: ''
    author: maciej+webinar-2022@prophecy.io
    createdAt: '2022-11-03 15:43:45'
    mode: batch
    physicalDatasets:
      dev:
        fabricId: 1034
        datasetType: Database
        description: ''
        author: maciej+webinar-2022@prophecy.io
        createdAt: '2022-11-03 15:43:45'
  datasets/final_report:
    name: final_report
    description: ''
    author: maciej+webinar-2022@prophecy.io
    createdAt: '2022-11-03 15:58:34'
    mode: batch
    physicalDatasets:
      dev:
        fabricId: 1034
        datasetType: Database
        description: ''
        author: maciej+webinar-2022@prophecy.io
        createdAt: '2022-11-03 15:58:34'
  datasets/silver_orders_sales_2:
    name: silver_orders_sales_2
    description: ''
    author: maciej+webinar-2022@prophecy.io
    createdAt: '2022-11-03 17:28:44'
    mode: batch
    physicalDatasets:
      dev:
        fabricId: 1034
        datasetType: Database
        description: ''
        author: maciej+webinar-2022@prophecy.io
        createdAt: '2022-11-03 17:28:44'
templates: {}
jobs:
  jobs/daily_job:
    name: daily_job
    description: ''
    fabricUID: 1034
    scheduler:
      Databricks: {}
    cloudProvider: null
    jobSize: small
    scheduleCron: 0 0 0 * * ? *
    timeout: null
    alerting:
      emails: ''
      onStart: false
      onSuccess: false
      onFailure: false
    pipelines:
    - pipelines/customers_cleanup
    - pipelines/orders_cleanup
    jobClusterMode:
      clusterMode:
        Multi: {}
      clusterId: null
    enabled: null
    createdAt: '2022-11-03 16:11:32'
    author: maciej+webinar-2022@prophecy.io
  jobs/monthly_job:
    name: monthly_job
    description: ''
    fabricUID: 1034
    scheduler:
      Databricks: {}
    cloudProvider: null
    jobSize: small
    scheduleCron: 0 0 0 1 * ? *
    timeout: null
    alerting:
      emails: maciej@prophecy.io
      onStart: false
      onSuccess: false
      onFailure: false
    pipelines:
    - pipelines/monthly_reporting
    jobClusterMode:
      clusterMode:
        Multi: {}
      clusterId: null
    enabled: null
    createdAt: '2022-11-03 17:34:22'
    author: maciej+webinar-2022@prophecy.io
libraries: []
subgraphs:
  subgraphs/enrich_customers:
    name: enrich_customers
    description: Enriches customers data
    author: maciej+webinar-2022@prophecy.io
    language: python
    mode: batch
    createdAt: '2022-11-03 15:51:39'
sqlModels: {}
sqlPipeline: null
dependencies: []
projectDependencies:
  '3890':
    projectUID: 3890
    projectName: ''
    repositoryPath: gitUri=http://gitserver:3000/pM1sUhx1_team_2518/pM1sUhx1_project_3890.git&subPath=&tag=saas_ingestion/1.0&projectSubscriptionProjectId=3890
    version: saas_ingestion/1.0
    author: null
    createdAt: '2022-11-28 16:09:32'
pipelineConfigurations: {}
